language: scala

scala:
  - 2.12.8
  - 2.11.12

env:
  - TRAVIS_JDK=8
  - TRAVIS_JDK=11

matrix:
  fast_finish: true
  allow_failures:
    - env: TRAVIS_JDK=11 # not fully supported but allows problem discovery

before_install: curl -Ls https://git.io/jabba | bash && . ~/.jabba/jabba.sh
install: jabba install "adopt@~1.$TRAVIS_JDK.0-0" && jabba use "$_" && java -Xmx32m -version

script:
  - sbt ++$TRAVIS_SCALA_VERSION validateCode
  - sbt ++$TRAVIS_SCALA_VERSION coverage test docs/test samples/test coverageReport
  - sbt ++$TRAVIS_SCALA_VERSION docs/validateDocs
  - sbt ++$TRAVIS_SCALA_VERSION mimaReportBinaryIssues

after_success: bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.jabba/jdk
    - $HOME/.sbt

before_cache:
  # Ensure changes to the cache aren't persisted
  - rm -rf $HOME/.ivy2/cache/com.typesafe.play/play-slick*
  # Delete all ivydata files since ivy touches them on each build
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" | xargs rm

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d2c8a242a2615f659595
    on_success: always
    on_failure: always
