name: Publish

on:
  push:
    branches: # Snapshots
      - 5.1.x
    tags: ["**"] # Releases
  release:
    types: [published]

jobs:
  publish-artifacts:
    name: Publish / Artifacts
    uses: playframework/.github/.github/workflows/publish.yml@v2
    secrets: inherit
