name: Publish

on:
  push:
    branches: # Snapshots
      - 5.3.x
    tags: ["**"] # Releases

jobs:
  publish-artifacts:
    name: Publish / Artifacts
    uses: playframework/.github/.github/workflows/publish.yml@v3
    secrets: inherit
